name = "Minia"
uuid = "fa43461c-3768-4c31-876a-d242d0244bb3"
authors = ["abap34 <uchi_ymgc@her0.jp> and contributors"]
version = "1.0.0-DEV"

[deps]
PEG = "12d937ae-5f68-53be-93c9-3a6f997a20a8"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
